### ISSUE TITLE
CudaAPIError: [34] Call to cuInit results in CUDA_ERROR_STUB_LIBRARY

### ISSUE THREAD

**Issue by mayur20169** [im-djh/CMD#4]
Package                  Version       Editable project location
------------------------ ------------- -------------------------
autocommand              2.2.2
backports.tarfile        1.2.0
ccimport                 0.4.3
certifi                  2024.8.30
charset-normalizer       3.4.0
clip                     1.0
contourpy                1.1.1
cumm-cu117               0.4.11
cycler                   0.12.1
easydict                 1.13
fire                     0.6.0
fonttools                4.53.1
fsspec                   2024.6.1
ftfy                     6.2.3
humanize                 4.10.0
idna                     3.10
imageio                  2.34.2
importlib_metadata       8.5.0
importlib_resources      6.4.0
inflect                  7.3.1
jaraco.collections       5.1.0
jaraco.context           5.3.0
jaraco.functools         4.0.1
jaraco.text              3.12.1
kiwisolver               1.4.5
lark                     1.2.2
lazy_loader              0.4
llvmlite                 0.41.1
matplotlib               3.7.5
more-itertools           10.3.0
mpmath                   1.3.0
networkx                 3.1
ninja                    1.11.1.1
numba                    0.58.1
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        9.1.0.70
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.20.5
nvidia-nvjitlink-cu12    12.6.20
nvidia-nvtx-cu12         12.1.105
opencv-python            4.10.0.84
packaging                24.1
pccm                     0.4.16
pcdet                    0.6.0+17198f6 /DATA2/mayur/mayur/CMD
pillow                   10.4.0
pip                      24.2
platformdirs             4.2.2
point-e                  0.0.0
portalocker              2.10.1
protobuf                 5.28.2
pybind11                 2.13.6
pyquaternion             0.9.9
PyWavelets               1.4.1
PyYAML                   6.0.2
regex                    2024.7.24
requests                 2.32.3
scikit-image             0.21.0
scipy                    1.10.1
setuptools               75.1.0
SharedArray              3.2.4
six                      1.16.0
spconv-cu117             2.3.6
sympy                    1.13.1
tensorboardX             2.6.2.2
termcolor                2.4.0
tifffile                 2023.7.10
tomli                    2.0.1
torch                    1.13.0+cu117
torchaudio               0.13.0+cu117
torchvision              0.14.0+cu117
tqdm                     4.66.5
triton                   3.0.0
typeguard                4.3.0
typing_extensions        4.12.2
urllib3                  2.2.3
wcwidth                  0.2.13
wheel                    0.44.0
zipp                     3.20.2

I am using python=3.8 and cuda==11.7 and torch==1.13.0+cu117.

After training, while doing evaluation I am getting this error.

My PyTorch version is compatible with cuda. I checked it.

<img width="1470" alt="Screenshot 2024-10-09 at 3 25 51 PM" src="https://github.com/user-attachments/assets/a8c6318a-7533-47e8-805d-1a7c89bb1c3d">

**Comment by wayyeah** [comment]
@mayur20169 , I found that there are some cu12 in your environment, such as nvidia-cublas-cu12, etc. It may be these that cause the problem, or it may be the version of numba that causes the problem. You can try numba==0.56.0 or 0.54.0.

**Comment by mayur20169** [comment]
@wayyeah Can you please specify the numba and numpy versions you used with python3.8 cuda==11.7

**Comment by wayyeah** [comment]
`Package                  Version      Editable project location
------------------------ ------------ -------------------------
ccimport                 0.4.2
certifi                  2023.11.17
charset-normalizer       3.3.2
cumm-cu113               0.4.11
easydict                 1.11
filelock                 3.13.1
fire                     0.5.0
fsspec                   2023.12.2
idna                     3.6
imageio                  2.33.1
importlib-metadata       7.0.1
Jinja2                   3.1.3
lark                     1.1.9
lazy_loader              0.3
llvmlite                 0.41.1
MarkupSafe               2.1.4
mpmath                   1.3.0
networkx                 3.1
ninja                    1.11.1.1
numba                    0.58.1
numpy                    1.24.4
nvidia-cublas-cu12       12.1.3.1
nvidia-cuda-cupti-cu12   12.1.105
nvidia-cuda-nvrtc-cu12   12.1.105
nvidia-cuda-runtime-cu12 12.1.105
nvidia-cudnn-cu12        8.9.2.26
nvidia-cufft-cu12        11.0.2.54
nvidia-curand-cu12       10.3.2.106
nvidia-cusolver-cu12     11.4.5.107
nvidia-cusparse-cu12     12.1.0.106
nvidia-nccl-cu12         2.18.1
nvidia-nvjitlink-cu12    12.3.101
nvidia-nvtx-cu12         12.1.105
opencv-python            4.9.0.80
packaging                23.2
pccm                     0.4.11
pcdet                    0.6.0+head   /mnt/32THHD/yw/xmuda
pillow                   10.2.0
pip                      23.3.1
portalocker              2.8.2
protobuf                 4.25.2
pybind11                 2.11.1
pypcd                    0.1.1        /mnt/32THHD/yw/pypcd
pyquaternion             0.9.9
python-lzf               0.2.4
PyWavelets               1.4.1
PyYAML                   6.0.1
requests                 2.31.0
scikit-image             0.21.0
scipy                    1.10.1
setuptools               68.2.2
SharedArray              3.2.3
six                      1.16.0
spconv-cu113             2.3.6
sympy                    1.12
tensorboardX             2.6.2.2
termcolor                2.4.0
tifffile                 2023.7.10
torch                    2.1.1+cu118
torchaudio               2.1.1+cu118
torchvision              0.16.1+cu118
tqdm                     4.66.1
triton                   2.1.0
typing_extensions        4.9.0
urllib3                  2.1.0
wheel                    0.41.2
zipp                     3.17.0`
This is my newly configured environment, which can be evaluated normally. You can compare the differences, which may be due to different torch versions@mayur20169
![image](https://github.com/user-attachments/assets/60eefd1f-ffb8-48b7-9e8e-0a4a3a5451fe)
